// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5WkxZ_mQxI0NkfJGvi6CIzbgDYFnwO4s',
    appId: '1:847192235087:web:4cf009c37314cd297c5e3a',
    messagingSenderId: '847192235087',
    projectId: 'tiffin-4e196',
    authDomain: 'tiffin-4e196.firebaseapp.com',
    storageBucket: 'tiffin-4e196.appspot.com',
    measurementId: 'G-7S2EWGRPZR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXdsQ_PWGtyMw0TdyhSoSlYISi_CzY_9w',
    appId: '1:847192235087:android:6c4e31fc8d09a11b7c5e3a',
    messagingSenderId: '847192235087',
    projectId: 'tiffin-4e196',
    storageBucket: 'tiffin-4e196.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDenwk5SzTCsg3CuzI3DslPUmjfV58LLaE',
    appId: '1:847192235087:ios:cd624aced5852d537c5e3a',
    messagingSenderId: '847192235087',
    projectId: 'tiffin-4e196',
    storageBucket: 'tiffin-4e196.appspot.com',
    iosBundleId: 'com.example.tiffin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDenwk5SzTCsg3CuzI3DslPUmjfV58LLaE',
    appId: '1:847192235087:ios:cd624aced5852d537c5e3a',
    messagingSenderId: '847192235087',
    projectId: 'tiffin-4e196',
    storageBucket: 'tiffin-4e196.appspot.com',
    iosBundleId: 'com.example.tiffin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5WkxZ_mQxI0NkfJGvi6CIzbgDYFnwO4s',
    appId: '1:847192235087:web:f5f19b19de94956c7c5e3a',
    messagingSenderId: '847192235087',
    projectId: 'tiffin-4e196',
    authDomain: 'tiffin-4e196.firebaseapp.com',
    storageBucket: 'tiffin-4e196.appspot.com',
    measurementId: 'G-SFSFDBX5EE',
  );
}
