// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCT4zbGaGHzpKK9BXD-I0DG4vok61j6uFk',
    appId: '1:837197401665:web:9c68387131695a2458c0c0',
    messagingSenderId: '837197401665',
    projectId: 'tiffin-dd53d',
    authDomain: 'tiffin-dd53d.firebaseapp.com',
    storageBucket: 'tiffin-dd53d.appspot.com',
    measurementId: 'G-G8FN17Y7ES',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCea8tl_l4ijtDEM5_hBp0yWKNUoe7Opg',
    appId: '1:837197401665:android:1740d26cfbcf6a3458c0c0',
    messagingSenderId: '837197401665',
    projectId: 'tiffin-dd53d',
    storageBucket: 'tiffin-dd53d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXitdIP9930VWCzbMCPkju2dY36I8WMUw',
    appId: '1:837197401665:ios:ecda0f778cb6186a58c0c0',
    messagingSenderId: '837197401665',
    projectId: 'tiffin-dd53d',
    storageBucket: 'tiffin-dd53d.appspot.com',
    iosBundleId: 'com.example.tiffin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXitdIP9930VWCzbMCPkju2dY36I8WMUw',
    appId: '1:837197401665:ios:ecda0f778cb6186a58c0c0',
    messagingSenderId: '837197401665',
    projectId: 'tiffin-dd53d',
    storageBucket: 'tiffin-dd53d.appspot.com',
    iosBundleId: 'com.example.tiffin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCT4zbGaGHzpKK9BXD-I0DG4vok61j6uFk',
    appId: '1:837197401665:web:5fbcaa7e2263fbf258c0c0',
    messagingSenderId: '837197401665',
    projectId: 'tiffin-dd53d',
    authDomain: 'tiffin-dd53d.firebaseapp.com',
    storageBucket: 'tiffin-dd53d.appspot.com',
    measurementId: 'G-F67JQBGFDX',
  );
}
